name       : libykneomgr
version    : 0.1.8
release    : 2
source     :
    - https://github.com/Yubico/libykneomgr/archive/libykneomgr-0.1.8.tar.gz : a2ba76dee657fa201e042057af1cded8141d989190cc93ced00b11c4ba356001
license    : LGPL-3.0
component  : programming
summary    : YubiKey NEO CCID Manager C Library
description: |
    YubiKey NEO CCID Manager C Library
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(libzip)
    - bzip2-devel
    - gengetopt
    - help2man
setup      : |
    touch ChangeLog
    %reconfigure --disable-static --with-backend=pcsc
build      : |
    %make
install    : |
    %make_install
